In [4]:
import pandas as pd

# Load dataset from Johns Hopkins University Github page
# with command pd.read_csv("datafile.csv")
covid_daily_report = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-24-2021.csv")

In [5]:
covid_daily_report

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-04-25 04:20:32,33.939110,67.709953,58730,2572,52392.0,3766.0,Afghanistan,150.866948,4.379363
1,NaN,NaN,NaN,Albania,2021-04-25 04:20:32,41.153300,20.168300,130409,2372,105016.0,23021.0,Albania,4531.551880,1.818893
2,NaN,NaN,NaN,Algeria,2021-04-25 04:20:32,28.033900,1.659600,120736,3198,84167.0,33371.0,Algeria,275.332106,2.648754
3,NaN,NaN,NaN,Andorra,2021-04-25 04:20:32,42.506300,1.521800,13024,124,12458.0,442.0,Andorra,16856.273863,0.952088
4,NaN,NaN,NaN,Angola,2021-04-25 04:20:32,-11.202700,17.873900,25492,577,23092.0,1823.0,Angola,77.562807,2.263455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3978,NaN,NaN,NaN,Vietnam,2021-04-25 04:20:32,14.058324,108.277199,2833,35,2490.0,308.0,Vietnam,2.910459,1.235439
3979,NaN,NaN,NaN,West Bank and Gaza,2021-04-25 04:20:32,31.952200,35.233200,290259,3151,260650.0,26458.0,West Bank and Gaza,5689.773192,1.085582
3980,NaN,NaN,NaN,Yemen,2021-04-25 04:20:32,15.552727,48.516388,6105,1175,2486.0,2444.0,Yemen,20.468741,19.246519
3981,NaN,NaN,NaN,Zambia,2021-04-25 04:20:32,-13.133897,27.849332,91317,1245,89403.0,669.0,Zambia,496.721163,1.363383
3982,NaN,NaN,NaN,Zimbabwe,2021-04-25 04:20:32,-19.015438,29.154857,38064,1556,35101.0,1407.0,Zimbabwe,256.100296,4.087852